=== edward-eric/WebTool/src/main/resource/connections/connection/definitions.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT module ((query)*) >
<!ATTLIST module
    name                     CDATA #REQUIRED
    description              CDATA #IMPLIED
>

<!ELEMENT query ((column+ , join*))>
<!ATTLIST query
    name CDATA #REQUIRED
    description CDATA #IMPLIED
    basetable CDATA #REQUIRED
    alias CDATA #REQUIRED
>


<!ELEMENT column (CDATA*)>
<!ATTLIST column
    name CDATA #REQUIRED
    columnname CDATA #REQUIRED
    orderby (true | false) "false"
    trend (true | false) "false"
    from CDATA #REQUIRED
>

<!ELEMENT join (constraint+)>
<!ATTLIST join
    name CDATA #REQUIRED
    table CDATA #REQUIRED
    outer (true | false) "false"
    alias CDATA #REQUIRED
>

<!ELEMENT constraint (CDATA*)>
<!ATTLIST constraint
    src CDATA #REQUIRED
    dest CDATA #REQUIRED
>

=== edward-eric/WebTool/src/main/resource/datareader-conf/components.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "definitions.dtd">

<module name="business" description="business case test">

   <query name="Scenario" description="Fecth scenario related columns"
          basetable="dtopt.scenario" alias="s">
          
          <column name="id"
                  columnname="scenarioid"
                  orderby="false"
                  from="s"/>
                  
          <column name="name"
                  columnname="name"
                  orderby="false"
                  from="s"/>
                  
          <column name="description"
                  columnname="description"
                  orderby="false"
                  from="s"/>
          
          <column name="goal"
                  columnname="goalvalue"
                  orderby="false"
                  from="s"/>
          
          <column name="type"
                  columnname="scenariotype"
                  orderby="false"
                  from="s"/>
                  
          <column name="startdate"
                  columnname="startdate"
                  orderby="false"
                  from="s"/>
          
          <column name="enddate"
                  columnname="enddate"
                  orderby="false"
                  from="s"/> 
          
   </query>



</module>
