=== edward-eric/WebTool/src/main/resource/preference-conf/viewdef.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT module ((views*, subviews*)) >
<!ATTLIST module
    description              CDATA #IMPLIED
>

<!ELEMENT views ((view)+)>
<!ATTLIST views
    description CDATA #IMPLIED
>

<!ELEMENT subviews ((subview)+)>
<!ATTLIST subviews
    description CDATA #IMPLIED
>

<!ELEMENT view ((subref)+)>
<!ATTLIST view
    id CDATA #REQUIRED
    title CDATA #REQUIRED
    description CDATA #IMPLIED
>
<!ELEMENT subref (CDATA)*>
<!ATTLIST subref
    id CDATA #REQUIRED
>

<!ELEMENT subview ((field)*)>
<!ATTLIST subview
    id CDATA #REQUIRED
    title CDATA #IMPLIED
    order CDATA #IMPLIED
    description CDATA #IMPLIED
>

<!ELEMENT field (CDATA)*>
<!ATTLIST field
    name CDATA #REQUIRED
    title CDATA #REQUIRED
    width CDATA #IMPLIED
    sortable (true | false) "true"
>

=== edward-eric/WebTool/src/main/resource/preference-conf/view.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "viewdef.dtd">

<module>

  <views>
  
      <view id="ScenarioResult">
          <subview id="Scenarios"/>
          <subview id="ScenarioRuns"/>
          <subview id="Results"/>
      </view>
   
  </views>
  
  <subviews>
     
     <subview id="Scenarios">
        <field name="ss" title="ss"/>
     </subview>
     
     <subview id="ScenarioRuns">
        <field name="ss" title="ss"/>
     </subview>
     
     <subview id="Results">
        <field name="ss" title="ss"/>
     </subview>
     
  </subviews>

   
   
</module>
